### ISSUE TITLE
开启后报错了，

### ISSUE THREAD

**Issue by wuaixiaoyao** [nabaonan/todos-action#1]
todos-action\vue2-vite-ts\vite.config.ts:41   return renameDir2 ?? `${compName[0].toLowerCase()}${compName.slice(1)}`;                      ^  SyntaxError: Unexpected token '?'     at Module._compile (internal/modules/cjs/loader.js:891:18)     at Object.require.extensions.<computed> [as .ts] (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\di st\node\chunks\dep-11db14da.js:75449:20)     at Module.load (internal/modules/cjs/loader.js:811:32)     at Function.Module._load (internal/modules/cjs/loader.js:723:14)     at Module.require (internal/modules/cjs/loader.js:848:19)     at require (internal/modules/cjs/helpers.js:74:18)     at loadConfigFromBundledFile (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-1 1db14da.js:75457:17)     at loadConfigFromFile (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-11db14da .js:75376:32)     at processTicksAndRejections (internal/process/task_queues.js:94:5)     at async resolveConfig (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-11db14d a.js:74965:28) error Command failed with exit code 1.

**Comment by nabaonan** [comment]
> todos-action\vue2-vite-ts\vite.config.ts:41 return renameDir2 ?? `${compName[0].toLowerCase()}${compName.slice(1)}`; ^ SyntaxError: Unexpected token '?' at Module._compile (internal/modules/cjs/loader.js:891:18) at Object.require.extensions. [as .ts] (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\di st\node\chunks\dep-11db14da.js:75449:20) at Module.load (internal/modules/cjs/loader.js:811:32) at Function.Module._load (internal/modules/cjs/loader.js:723:14) at Module.require (internal/modules/cjs/loader.js:848:19) at require (internal/modules/cjs/helpers.js:74:18) at loadConfigFromBundledFile (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-1 1db14da.js:75457:17) at loadConfigFromFile (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-11db14da .js:75376:32) at processTicksAndRejections (internal/process/task_queues.js:94:5) at async resolveConfig (D:\Pwrd\todos-action\vue2-vite-ts\node_modules\vite\dist\node\chunks\dep-11db14d a.js:74965:28) error Command failed with exit code 1.

这个是开发模式还是build时候报的错

**Comment by nabaonan** [comment]
再试试吧，早上改了一下
